# generated
name: x_utbvbj2xi3efcucn
on:
  workflow_dispatch: {}
  workflow_call: {}
permissions:
  actions: write
  contents: read
  id-token: write
jobs:
  x_z3cxjxnc3vjx5nzj:
    name: x_z3cxjxnc3vjx5nzj
    uses: ./.github/workflows/x_6g3j7dfbchvrgqlt.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_663w7xmbwihpfl77:
    name: x_663w7xmbwihpfl77
    uses: ./.github/workflows/x_nil27mi6ztwowsj6.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_shytvnu47243btzl:
    name: x_shytvnu47243btzl
    uses: ./.github/workflows/x_7ksiayznvwfeetb5.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_6jhbnboclb7mpakq:
    name: x_6jhbnboclb7mpakq
    uses: ./.github/workflows/x_keflvgdze6cpfxml.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_lvnx7ircdgfnfe7n:
    name: x_lvnx7ircdgfnfe7n
    uses: ./.github/workflows/x_u6gjowpemu2pto6l.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_bmnbke3iudnfyarx:
    name: x_bmnbke3iudnfyarx
    uses: ./.github/workflows/x_2lpvqy7uyc3o6zcv.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_yjoazfvnlh4cwg3y:
    name: x_yjoazfvnlh4cwg3y
    uses: ./.github/workflows/x_3b4uxpln25d3bc3v.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_agpniy7osr5b67vb:
    name: x_agpniy7osr5b67vb
    uses: ./.github/workflows/x_e64iyzdknz6oeucx.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_5gqgz3kf3t6y4zlh:
    name: x_5gqgz3kf3t6y4zlh
    uses: ./.github/workflows/x_brwlbt3ulr5o4r3o.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_x5hznrfqeh27t3s5:
    name: x_x5hznrfqeh27t3s5
    uses: ./.github/workflows/x_t3kbz6zztw454upi.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_wu7mbgbujz3b3hah:
    name: x_wu7mbgbujz3b3hah
    uses: ./.github/workflows/x_yhhv7xiicgbyfnyf.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_ychoet7nsaw2nzp4:
    name: x_ychoet7nsaw2nzp4
    uses: ./.github/workflows/x_6y4swyfpoo5kdhud.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_356zl3rgxwmc33cq:
    name: x_356zl3rgxwmc33cq
    uses: ./.github/workflows/x_7qoyxt4qsjsh6mi4.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_wb5s55ox37v23yt3:
    name: x_wb5s55ox37v23yt3
    uses: ./.github/workflows/x_n6zjeg7qfc3sawr2.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_u6thnfysgngse5ch:
    name: x_u6thnfysgngse5ch
    uses: ./.github/workflows/x_ucexiv26tivdamhg.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_kfsxjpzqpqgnswii:
    name: x_kfsxjpzqpqgnswii
    uses: ./.github/workflows/x_hrkligi7iftqzbzz.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_j2avovvoew5a2ie2:
    name: x_j2avovvoew5a2ie2
    uses: ./.github/workflows/x_nzxhk3cz4pdpm5za.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
  x_zxwqo5tcgtxhktb7:
    name: x_zxwqo5tcgtxhktb7
    uses: ./.github/workflows/x_puaiotvkaaqq55jd.yml
    permissions:
      actions: write
      contents: read
      id-token: write
    secrets: inherit
concurrency:
  group: x_utbvbj2xi3efcucn
  cancel-in-progress: false
